// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmYPXpZ_0hrGZtg28V_Oa49cgnu9Bevm4',
    appId: '1:1011521839302:web:8e0b1103dd433206b8b7c7',
    messagingSenderId: '1011521839302',
    projectId: 'countryfirebase-d966e',
    authDomain: 'countryfirebase-d966e.firebaseapp.com',
    storageBucket: 'countryfirebase-d966e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWR_iIBRE6b9tIMMmywqRz8oQqTKp0d1I',
    appId: '1:1011521839302:android:93fc8d8711fc2afcb8b7c7',
    messagingSenderId: '1011521839302',
    projectId: 'countryfirebase-d966e',
    storageBucket: 'countryfirebase-d966e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfbZAk_bsJU22EIrwn03NeuKRE-6IJjAA',
    appId: '1:1011521839302:ios:24a4a00d637e8f1ab8b7c7',
    messagingSenderId: '1011521839302',
    projectId: 'countryfirebase-d966e',
    storageBucket: 'countryfirebase-d966e.appspot.com',
    iosBundleId: 'com.example.restCountries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfbZAk_bsJU22EIrwn03NeuKRE-6IJjAA',
    appId: '1:1011521839302:ios:24a4a00d637e8f1ab8b7c7',
    messagingSenderId: '1011521839302',
    projectId: 'countryfirebase-d966e',
    storageBucket: 'countryfirebase-d966e.appspot.com',
    iosBundleId: 'com.example.restCountries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmYPXpZ_0hrGZtg28V_Oa49cgnu9Bevm4',
    appId: '1:1011521839302:web:3c333c08b293c447b8b7c7',
    messagingSenderId: '1011521839302',
    projectId: 'countryfirebase-d966e',
    authDomain: 'countryfirebase-d966e.firebaseapp.com',
    storageBucket: 'countryfirebase-d966e.appspot.com',
  );

}